name: gate_env
channels:
  - defaults
dependencies:
  - python=3.10
  - torchaudio==2.4.0
  - pytorch==2.4.0
  - torchvision==0.19.0
  - pytorch-cuda=11.8
  - numpy=1.24
  - openpyxl=3.1.2
  - h5py
  - conda-forge::optuna
